title: Tongrui Zhang's Homepage
page-top-title: Tongrui Zhang
sidebar-name: Tongrui Zhang (张桐瑞)
sidebar-affiliation: Shandong University of Finance and Economics (SDUFE)
sidebar-location: Jinan / Wuhan, China
sidebar-email: Email
sidebar-email-link: mailto:ac@r-r.cc
sidebar-github: GitHub
sidebar-scholar: Google Scholar
sidebar-scholar-link: '#'
sidebar-orcid: ORCID
sidebar-orcid-link: '#'
sidebar-rg: ResearchGate
sidebar-rg-link: '#'
copyright-text: © Tongrui Zhang 2026. All Rights Reserved.
