title: Tongrui Zhang's Homepage
page-top-title: Tongrui Zhang
sidebar-name: Tongrui Zhang (张桐瑞)
sidebar-affiliation: Incoming Direct Ph.D. Student at Huazhong University of Science and Technology (HUST), working on computer vision and deep learning.
sidebar-location: Wuhan / Jinan, China
sidebar-email: tongruizhang@hust.edu.cn
sidebar-email-link: mailto:tongruizhang@hust.edu.cn
sidebar-github: Charlotte5622
sidebar-scholar: Google Scholar
sidebar-scholar-link: '#'
sidebar-orcid: ORCID
sidebar-orcid-link: '#'
sidebar-rg: ResearchGate
sidebar-rg-link: '#'
copyright-text: '&copy; Tongrui Zhang 2026. All Rights Reserved.'
