title: Tong Zhang's Homepage
page-top-title: Tong Zhang (张桐瑞)
top-section-bg-text: Explore, Build, Research
home-subtitle: Tongrui Zhang (张桐瑞)&ensp;|&ensp;
copyright-text: '&copy; Tong Zhang 2026. All Rights Reserved.'
